import style from "../../styles/index.module.scss";
import styles from "../../styles/Video/Video.module.scss";
import {NextPage} from "next";
import {useRouter} from "next/router";
import Head from "next/head";
import React, {useEffect} from "react";
import {useDispatch} from "react-redux";
import {Header} from "../Component/Header/Header";
import {getVideo} from "../redux/video/thunks";

const Video:NextPage = () => {
  const dispatch = useDispatch();
  const router = useRouter();
  const {pid} = router.query;
  let imaOptions = {
		adTagUrl:process.env.VOD_PREROLL,
		adLabel:"",
		autoPlayAdBreaks:true,
	}
  useEffect(() => {
    if(pid && pid.length > 1){
      dispatch(getVideo(parseInt(pid[1])));
    }
  },[dispatch,pid])

	return(
    <div className={style.App}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../swiper_favicon.ico"/>
      </Head>
      <div className={styles.video}>
        <Header/>
        <div className={styles.video_content}>
          <main className={styles.page}>
            <div className={styles.body}>

            </div>
          </main>
        </div>
      </div>
    </div>
  )
}

export default Video;