import styles from "../../styles/Channel/Channel.module.scss";
import style from "../../styles/index.module.scss";
import {Swiper,SwiperSlide} from "swiper/react";
import {NextPage} from "next";
import {useRouter} from "next/router";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {useDispatch,useSelector} from "react-redux";
import React,{useEffect,useState} from "react";
import {getContent} from "../redux/category/thunks";
import {TypeHeader} from "../components/TypeHeader/TypeHeader";
import {Footer} from "../components/Footer/Footer";
import {Breadcrumb} from "../components/Breadcrumb/Breadcrumb";
import {WideCategoryVideoBlock} from "../components/WideCategoryVideoBlock/WideCategoryVideoBlock";
import {CategoryVideoBlock} from "../components/CategoryVideoBlock/CategoryVideoBlock";
import {IRootState} from "../store";

const SubCategory:NextPage = () => {
  const dispatch = useDispatch();
  const router = useRouter();
  const {pid} = router.query;
  const videos = useSelector((state:IRootState) => state.category.video);
  const categories = useSelector((state:IRootState) => state.header.category);
  const subCategories = useSelector((state:IRootState) => state.header.subCategory);
  const subcategories = useSelector((state:IRootState) => state.header.subCategory);
  const [search,setSearch] = useState(false);
  const [scrollHeight,setScrollHeight] = useState(0);
  const categoryId = (subcategories.filter((subcategory) => subcategory.name_cn.split("．").join("").split("・").join("") === (pid && pid[0])))[0]?.cate_id;
  useEffect(() => {
    dispatch(getContent(categoryId));
  },[dispatch,categoryId])
  useEffect(() => {
		function updateScrollHeight(){
			setScrollHeight(window.pageYOffset);
		}
		window.addEventListener("scroll",updateScrollHeight);
		return () => {
      window.removeEventListener("scroll",updateScrollHeight);
    }
	},[scrollHeight])

	return(
    <div className={`${styles.channel} ${styles.pid}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/swiper_favicon.ico"/>
      </Head>
      <TypeHeader search={search} setSearch={setSearch}/>
      <header className={`${scrollHeight > 10 ? styles.category_header_scroll : styles.category_header} ${search ? styles.category_header_for_searching : ""}`}>
        <div className={styles.category_header_width}>
          <div className={styles.flex_header}>
            <h2>{categories.filter((category) => category.cate_id === categoryId).map((category) => category.name_cn)}</h2>
            <div className={styles.shadow}>
              <div className={styles.sub_category_bar_horizontal_scroll}>
                <nav className={styles.sub_category_bar}>
                  <ul className={styles.sub_category_items}>
                    <li className={styles.sub_category_item}>
                      <Link href={`/category/${categories.filter((category) => category.cate_id === categoryId).map((category) => category.name_en.toLowerCase().split(" ").join("").split("/").join(""))}`}>
                        <a>全部</a>
                      </Link>
                    </li>
                    {
                      subCategories.filter((subCategory) => subCategory.cate_id === categoryId).map((subCategory,index) => {
                        return(
                          <li className={`${styles.sub_category_item} ${subCategory.name_cn.split("．").join("").split("・").join("") === (pid && pid[0]) ? styles.active : ""}`} key={index}>
                            <Link href={`/channel/${subCategory.name_cn.split("．").join("").split("・").join("")}/${subCategory.subcate_id}`}>
                              <a>{subCategory.name_cn.split("．").join("").split("・").join("")}</a>
                            </Link>
                          </li>
                        )
                      })
                    }
                  </ul>
                </nav>
              </div>
              </div>
          </div>
        </div>
      </header>
      <div className={`${search ? styles.channel_content_for_searching : scrollHeight > 10 ? styles.channel_content_scroll : styles.channel_content} ${style.App}`}>
        <main className={styles.page}>
          <div className={styles.breadcrumb}>
            <Breadcrumb pid={pid} videos={videos} categories={categories} subCategories={subcategories} type="subCategory"/>
          </div>
          <div className={styles.body}>
            <div className={styles.main_content}>
              <div className={`${styles.carousel} subcategory_carousel`}>
                <Swiper
                  navigation
                  pagination={{clickable:true}}
                  spaceBetween={5}
                  loop
                  autoplay={{delay:3000,disableOnInteraction:false}}
                >
                  {
                    videos.filter((video) => video.subcate_name.split("．").join("").split("・").join("") === (pid && pid [0])).filter((video,index) => index < 6).map((video) =>
                      <SwiperSlide key={video.id}>
                        <div className={styles.video_block}>
                          <Link href={`/video/${video.subcate_name.split("．").join("").split("・").join("")}/${video.id}/${video.title}`}>
                            <a className={styles.video_block_link}>
                              <div className={styles.image}>
                                <Image src={video.pic_url} alt="video detail" layout="fill"/>
                              </div>
                              <div className={styles.video_description}>
                                <div className={styles.carousel_category}>
                                  <Link href={`/category/${categories.filter((category) => category.cate_id === video.cate_id).map((category) => category.name_en)}`}>
                                    <a>{categories.filter((category) => category.cate_id === video.cate_id).map((category) => category.name_cn)}</a>
                                  </Link>
                                </div>
                                <header className={styles.video_title}>{video.title}</header>
                                <div className={styles.display_date}>{video.display_date}</div>
                              </div>
                            </a>
                          </Link>
                        </div>
                      </SwiperSlide>
                    )
                  }
                </Swiper>
              </div>
            </div>
            <div className={styles.main_video_list}>
              <div className={styles.video_list}>
                {videos.filter((video) => video.subcate_name.split("．").join("").split("・").join("") === (pid && pid [0])).filter((video,index) => index === 6).map((video) =>
                  <WideCategoryVideoBlock video={video} main={true} key={video.id}/>
                )}
                {videos.filter((video) => video.subcate_name.split("．").join("").split("・").join("") === (pid && pid [0])).filter((video,index) => index > 6 && index < 10).map((video) =>
                  <WideCategoryVideoBlock video={video} key={video.id}/>
                )}
                {videos.filter((video) => video.subcate_name.split("．").join("").split("・").join("") === (pid && pid [0])).filter((video,index) => index > 9 && index < 13).map((video) =>
                  <CategoryVideoBlock video={video} key={video.id}/>
                )}
              </div>
            </div>
          </div>
        </main>
      </div>
      <Footer/>
    </div>
  )
}

export default SubCategory;