import style from "../styles/Home/Home.module.scss";
import {library} from "@fortawesome/fontawesome-svg-core";
import {fab} from "@fortawesome/free-brands-svg-icons";
import {fas} from "@fortawesome/free-solid-svg-icons";
import {getHeader} from "./redux/header/thunks";
import {Header} from "./Header/Header";
import {Carousel} from "react-bootstrap";
import {useDispatch, useSelector} from "react-redux";
import React,{useEffect} from "react";
import SwiperCore,{Navigation,Pagination,Scrollbar} from "swiper";
import {Swiper,SwiperSlide} from "swiper/react";
import {getHomeDetail} from "./redux/home/thunks";
import {IRootState} from "./store";
import {ComponentHeader} from "./ComponentHeader/ComponentHeader";
import {VideoBlock} from "./VideoBlock/VideoBlock";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/index.module.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import "swiper/swiper-bundle.min.css";
import "swiper/swiper.min.css";
import {HomeCategoryBlock} from "./HomeCategoryBlock/HomeCategoryBlock";
import {NextPage} from "next";
library.add(fab,fas);
SwiperCore.use([Navigation,Pagination,Scrollbar]);

const Home:NextPage = () => {
	const dispatch = useDispatch();
	const videoDetail = useSelector((state:IRootState) => state.home.video);
	const categoryName = useSelector((state:IRootState) => state.header.category);
	useEffect(() => {
		dispatch(getHomeDetail());
	},[dispatch])
  useEffect(() => {
		dispatch(getHeader())
	},[dispatch])

	return(
		<div className={`${style.home} ${styles.App}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Header/>
			<div className={style.advertisement}></div>
			<main className={style.page}>
				<div className={style.body}>
					<div className={style.main_content}>
						<Carousel className={style.main_carousel}>
							{
								videoDetail.filter((video,index) => index < 3)
								.map((video) =>
									<Carousel.Item key={video.id}>
                    <Link href={`/video/${video.id}`}>
                      <a>
                        <div className="image">
                          <Image className="d-block w-100" src={video.pic_url} alt="slide" layout="fill"/>
                        </div>
                        <Carousel.Caption>
                          <div className="carousel_category">
                            <Link href={`/${categoryName.filter((category) => category.cate_id === video.cate_id).map((category) => category.name_en)}`}>
                              <a>{categoryName.filter((category) => category.cate_id === video.cate_id).map((category) => category.name_cn)}</a>
                            </Link>
                          </div>
                          <h6>{video.title}</h6>
                        </Carousel.Caption>
                      </a>
                    </Link>
									</Carousel.Item>
								)
							}
						</Carousel>
						<div className={style.free_content}>
							<section className={style.free_content_section}>
								<ComponentHeader header="免費任睇"/>
								<div className={style.video_list}>
									{
										videoDetail.filter((video,index) => index < 3)
										.map((video) => {
                      // return同括號一定要同一衘
                      return(
                        <VideoBlock key={video.id} video={video} blockPerRow={3} titleHeight={40}/>
                      )
                    })
									}
									{
										videoDetail.filter((video,index) => index > 8 && index < 12)
										.map((video) => {
                      return(
                        <VideoBlock key={video.id} video={video} blockPerRow={3} titleHeight={40}/>
                      )
                    })
									}
								</div>
							</section>
						</div>
						<div className={style.trending_content}>
							<section className={style.trending_content_section}>
								<ComponentHeader header="熱門影片"/>
								<Swiper
									spaceBetween={5}
									slidesPerView={2}
									slidesPerGroup={2}
									navigation
									pagination={{clickable:true}}
								>
									{
										videoDetail.filter((video,index) => index < 3)
										.map((video) => {
                      return(
                        <SwiperSlide className={style.video_block} key={video.id}>
                          <VideoBlock video={video} blockPerRow={1}/>
                        </SwiperSlide>
										  )
                    })
									}
                  {
										videoDetail.filter((video,index) => index > 8 && index < 10)
										.map((video) => {
                      return(
                        <SwiperSlide className={style.video_block} key={video.id}>
                          <VideoBlock video={video} blockPerRow={1}/>
                        </SwiperSlide>
										  )
                    })
									}
								</Swiper>
							</section>
						</div>
						<div className={style.advice_content}>
							<section className={style.advice_content_section}>
								<ComponentHeader header="推薦影片"/>
								<Swiper
									spaceBetween={5}
									slidesPerView={2}
									slidesPerGroup={2}
									navigation
									pagination={{clickable:true}}
								>
									{
										videoDetail.filter((video,index) => index < 3)
										.map((video) =>
											<SwiperSlide className={style.video_block} key={video.id}>
												<VideoBlock video={video} blockPerRow={1}/>
											</SwiperSlide>
										)
									}
                  {
										videoDetail.filter((video,index) => index > 8 && index < 10)
										.map((video) => {
                      return(
                        <SwiperSlide className={style.video_block} key={video.id}>
                          <VideoBlock video={video} blockPerRow={1}/>
                        </SwiperSlide>
										  )
                    })
									}
								</Swiper>
							</section>
						</div>
					</div>
					<aside className={style.sidebar}>
						<div className={style.latest_content}>
							<section className={style.latest_content_section}>
								<ComponentHeader header="最新影片"/>
                <div className={style.video_list_scroll}>
                  <div className={style.video_list}>
                    {
                      videoDetail.filter((video,index) => index < 3)
                      .map((video) =>
                        <VideoBlock key={video.id} video={video} blockPerRow={1}/>
                      )
                    }
                    {
                      videoDetail.filter((video,index) => index > 8 && index < 12)
                      .map((video) =>
                        <VideoBlock key={video.id} video={video} blockPerRow={1}/>
                      )
                    }
                  </div>
                </div>
							</section>
						</div>
            <div className={style.trending_topic}>
              <section className={style.trending_topic_section}>
                <header>熱門話題</header>
                <ol className={style.trending_tag_list}>
                  <li className={style.trending_tag_list_item}>1. 李雲迪</li>
                  <li className={style.trending_tag_list_item}>1. 李雲迪</li>
                  <li className={style.trending_tag_list_item}>1. 李雲迪</li>
                  <li className={style.trending_tag_list_item}>1. 李雲迪</li>
                  <li className={style.trending_tag_list_item}>1. 李雲迪</li>
                  <li className={style.trending_tag_list_item}>1. 李雲迪</li>
                </ol>
              </section>
            </div>
					</aside>
				</div>
			</main>
      <div className={style.member_extended_content}>
        <section className={style.member_extended_content_section}>
          <ComponentHeader header="會員專區" color="#fff" padding={0} borderColor="#4d535a"/>
          <div className={style.video_list}>
            {
              videoDetail.filter((video,index) => index < 3)
              .map((video) => {
                return(
                  <Link href={`/video/${video.id}`} key={video.id}>
                    <a className={style.video_block}>
                      <div className={style.image}>
                        <Image src={video.pic_url} alt="video-detail" className="d-block w-100" layout="fill"/>
                      </div>
                      <div className={style.video_description}>
                        <header className={style.video_title}>{video.title}</header>
                        <div className={style.display_date}>{video.display_date}</div>
                      </div>
                    </a>
                  </Link>
                )
              })
            }
            {
              videoDetail.filter((video,index) => index > 8 && index < 10)
              .map((video) => {
                return(
                  <Link href={`/video/${video.id}`} key={video.id}>
                    <a className={style.video_block}>
                      <div className={style.image}>
                        <Image src={video.pic_url} alt="video-detail" className="d-block w-100" layout="fill"/>
                      </div>
                      <div className={style.video_description}>
                        <header className={style.video_title}>{video.title}</header>
                        <div className={style.display_date}>{video.display_date}</div>
                      </div>
                    </a>
                  </Link>
                )
              })
            }
          </div>
        </section>
      </div>
      <div className={style.large_category_blocks}>
        {categoryName.map((category) => (
          <HomeCategoryBlock key={category.cate_id} category={category}/>
        ))}
      </div>
		</div>
	)
}

export default Home;